/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:58292846-ecb6-465f-a791-745a3e4fc551",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IvllBE2DS",
    "aws_user_pools_web_client_id": "18duvsvsaf3gncibg1qt909h43",
    "oauth": {}
};


export default awsmobile;
